# vi: set ft=yaml.ansible :
---
- name: Bootstrap
  become: true
  run_once: true
  hosts: controller
  tasks:
    - name: Install kubeadm configuration
      ansible.builtin.template:
        dest: /etc/kubeadm/config.yml
        mode: "0600"
        src: etc/kubeadm/config.yml

    - name: Install kube-vip configuration
      ansible.builtin.template:
        dest: /etc/kubernetes/manifests/kube-vip.yml
        mode: "0600"
        src: etc/kubernetes/manifests/kube-vip.yml

    - name: Create certificate key
      register: certificate_key
      changed_when: false
      ansible.builtin.command: |-
        kubeadm certs certificate-key

    - name: Initialize cluster
      register: init
      changed_when: init.rc == 0
      failed_when: init.rc != 0 and "/etc/kubernetes/manifests/kube-apiserver.yaml already exists" not in init.stderr
      ansible.builtin.command: |-
        kubeadm init
        --config=/etc/kubeadm/config.yml

    - name: Retrieve CA cert hash
      changed_when: false
      register: ca_cert_hash
      args:
        executable: /bin/bash
      ansible.builtin.shell: |-
        set -euo pipefail
        openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt |
        openssl rsa -pubin -outform der 2>/dev/null |
        openssl dgst -sha256 -hex |
        sed 's/^.* //'

    - name: Upload kubernetes certs
      changed_when: false
      ansible.builtin.command: |-
        kubeadm init phase upload-certs --upload-certs
        --certificate-key={{ certificate_key.stdout }}

    - name: Create join token
      register: join_token
      changed_when: false
      ansible.builtin.command: |-
        kubeadm token create

- name: Control plane
  become: true
  hosts: controller
  tasks:
    - name: Join node to control plane
      register: join
      when: ansible_host != groups['controller'][0]
      changed_when: join.rc == 0
      failed_when: join.rc != 0 and "[preflight] Running pre-flight checks" not in join.stdout
      ansible.builtin.command: |-
        kubeadm join
        {{ control_plane_endpoint }}:6443
        --control-plane
        --token={{ join_token.stdout }}
        --discovery-token-ca-cert-hash=sha256:{{ ca_cert_hash.stdout }}
        --certificate-key={{ certificate_key.stdout }}

    - name: Install kube-vip configuration
      ansible.builtin.template:
        dest: /etc/kubernetes/manifests/kube-vip.yml
        mode: "0600"
        src: etc/kubernetes/manifests/kube-vip.yml

    - name: Create kubeconfig path
      ansible.builtin.file:
        group: root
        mode: "0700"
        owner: root
        path: /root/.kube
        state: directory

    - name: Link admin credentials for root user
      ansible.builtin.file:
        dest: /root/.kube/config
        group: root
        mode: "0600"
        owner: root
        src: /etc/kubernetes/admin.conf
        state: link

- name: Worker plane
  become: true
  hosts: worker
  tasks:
    - name: Join node to worker plane
      register: join_worker
      changed_when: join_worker.rc == 0
      failed_when: join_worker.rc != 0 and "[preflight] Running pre-flight checks" not in join_worker.stdout
      ansible.builtin.command: |-
        kubeadm join
        {{ control_plane_endpoint }}:6443
        --token={{ hostvars[groups['controller'][0]].join_token.stdout }}
        --discovery-token-ca-cert-hash=sha256:{{ hostvars[groups['controller'][0]].ca_cert_hash.stdout }}

- name: Label worker nodes
  become: true
  run_once: true
  hosts: controller
  tasks:
    - name: Add worker node role
      register: role_worker
      loop: "{{ groups['worker'] }}"
      changed_when: role_worker.rc == 0
      failed_when: role_worker.rc != 0 and "already has a value" not in role_worker.stderr
      ansible.builtin.command: |-
        kubectl label nodes {{ item }} node-role.kubernetes.io/worker=worker

- name: Download kubeconfig
  become: true
  run_once: true
  hosts: controller
  tasks:
    - name: Download kubeconfig
      ansible.builtin.fetch:
        flat: true
        src: /etc/kubernetes/admin.conf
        dest: build/{{ cluster_name }}.yml
