---
rpm_install:
  - bash-completion
  - conntrack-tools
  - container-selinux
  - ethtool 
  - iproute-tc
  # - iptables-nft
  - qemu-guest-agent
  - socat

rpm_remove:
  - man-db
  - pinentry
  - plymouth
  - polkit
  - slang
  - sssd-client
  - sssd-common
  - sssd-kcm
  - sssd-nfs-idmap
  - teamd
