---
kernel_modules:
  - br_netfilter
  - overlay

sysctl_parameters:
  - key: net.ipv6.conf.all.forwarding
    value: 1
  - key: net.ipv4.ip_forward
    value: 1
  - key: kernel.keys.root_maxbytes
    value: 25000000
  - key: kernel.keys.root_maxkeys
    value: 1000000
  - key: kernel.panic
    value: 10
  - key: kernel.panic_on_oops
    value: 1
  - key: vm.overcommit_memory
    value: 1
  - key: vm.panic_on_oom
    value: 0
  - key: net.bridge.bridge-nf-call-iptables
    value: 1
  - key: net.bridge.bridge-nf-call-ip6tables
    value: 1

go_arch: "{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}"
go_arch_map:
  i386: '386'
  x86_64: 'amd64'
  aarch64: 'arm64'
  armv7l: 'armv7'
  armv6l: 'armv6'
