# vi: set ft=yaml.ansible :
---
- name: Push dnf configuration
  ansible.builtin.copy:
    dest: /etc/dnf/dnf.conf
    group: root
    mode: "0644"
    owner: root
    src: etc/dnf/dnf.conf

- name: Install epel repository
  ansible.builtin.dnf:
    name: epel-release
    state: present

- name: Install tools
  ansible.builtin.dnf:
    name: "{{ rpm_install }}"
    state: present

- name: Clear packages
  ansible.builtin.dnf:
    pkg: "{{ rpm_remove }}"
    autoremove: true
    state: absent

- name: Upgrade system
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_only: true

- name: Enable QEMU guest agent
  ansible.builtin.systemd:
    enabled: true
    name: qemu-guest-agent

- name: Disable unnecessary services
  loop: "{{ systemd_disable }}"
  ansible.builtin.systemd:
    enabled: false
    name: "{{ item }}"
