# vi: set ft=yaml.ansible :
---
- name: Remove unwanted configuration files
  loop:
    - /etc/apt/apt.conf.d/70debconf
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent

- name: Push apt configuration
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/99minify
    group: root
    mode: "0644"
    owner: root
    src: etc/apt/apt.conf.d/99minify

- name: Push apt sources list
  ansible.builtin.template:
    dest: /etc/apt/sources.list
    group: root
    mode: "0644"
    owner: root
    src: etc/apt/sources.list

- name: Clear packages
  ansible.builtin.apt:
    pkg: "{{ apt_remove }}"
    purge: true
    state: absent

- name: Upgrade system
  ansible.builtin.apt:
    autoclean: true
    autoremove: true
    update_cache: true
    upgrade: dist

- name: Install tools
  ansible.builtin.apt:
    pkg: "{{ apt_install }}"
    state: present

- name: Enable QEMU guest agent
  ansible.builtin.systemd:
    enabled: true
    name: qemu-guest-agent

- name: Disable unnecessary services
  loop: "{{ systemd_disable }}"
  ansible.builtin.systemd:
    enabled: false
    name: "{{ item }}"
