---
- name: create systemd directory
  ansible.builtin.file:
    group: root
    mode: 0755
    owner: root
    path: /usr/local/lib/systemd/system
    state: directory

- name: remove unwanted configuration files
  loop:
    - /etc/apt/apt.conf.d/70debconf
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent

- name: push apt configuration
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/99minify
    group: root
    mode: 0644
    owner: root
    src: etc/apt/apt.conf.d/99minify

- name: push apt sources list
  ansible.builtin.template:
    dest: /etc/apt/sources.list
    group: root
    mode: 0644
    owner: root
    src: etc/apt/sources.list

- name: push kernel module configuration
  notify: reload modules
  ansible.builtin.template:
    dest: /etc/modules-load.d/kubernetes.conf
    group: root
    mode: 0644
    owner: root
    src: etc/modules-load.d/kubernetes.conf

- name: push sysctl configuration
  notify: reload sysctl
  ansible.builtin.template:
    dest: /etc/sysctl.d/99-kubernetes.conf
    group: root
    mode: 0644
    owner: root
    src: etc/sysctl.d/99-kubernetes.conf

- name: clear packages
  ansible.builtin.apt:
    pkg: "{{ apt_remove }}"
    purge: true
    state: absent

- name: upgrade system
  ansible.builtin.apt:
    autoclean: true
    autoremove: true
    update_cache: true
    upgrade: dist

- name: install tools
  ansible.builtin.apt:
    pkg:
      - conntrack
      - ethtool
      - qemu-guest-agent
      - socat
      - bash-completion
    state: present

- name: enable QEMU guest agent
  ansible.builtin.systemd:
    enabled: true
    name: qemu-guest-agent
