# vi: set ft=yaml.ansible :
---
- name: Create systemd directories
  ansible.builtin.file:
    group: root
    mode: "0755"
    owner: root
    path: /usr/local/lib/systemd/system
    state: directory

- name: Push kernel module configuration
  notify: Reload modules
  ansible.builtin.template:
    dest: /etc/modules-load.d/kubernetes.conf
    group: root
    mode: "0644"
    owner: root
    src: etc/modules-load.d/kubernetes.conf

- name: Push sysctl configuration
  notify: Reload sysctl
  ansible.builtin.template:
    dest: /etc/sysctl.d/99-kubernetes.conf
    group: root
    mode: "0644"
    owner: root
    src: etc/sysctl.d/99-kubernetes.conf

- name: Run os specific tasks
  ansible.builtin.include_tasks: preflight/{{ ansible_distribution | lower }}.yml
