---
- name: reload sysctl
  ansible.builtin.systemd:
    name: systemd-sysctl
    state: restarted

- name: reload modules
  ansible.builtin.systemd:
    name: systemd-modules-load
    state: restarted
