# vi: set ft=yaml.ansible :
---
- name: Reload modules
  ansible.builtin.systemd:
    name: systemd-modules-load
    state: restarted

- name: Reload sysctl
  ansible.builtin.systemd:
    name: systemd-sysctl
    state: restarted
