# vi: set ft=yaml.ansible :
---
- name: Import os specific variables
  ansible.builtin.include_vars: vars/{{ ansible_distribution | lower }}.yml

- name: Preflight
  ansible.builtin.include_tasks: preflight/main.yml

- name: Install completion scripts
  ansible.builtin.include_tasks: install/bash_completion.yml

- name: Install CNI plugins
  when: install_cni_plugins
  ansible.builtin.include_tasks: install/cni_plugins.yml

- name: Install containerd
  when: install_containerd
  ansible.builtin.include_tasks: install/containerd.yml

- name: Install cri_tools
  when: install_cri_tools
  ansible.builtin.include_tasks: install/cri_tools.yml

- name: Install etcd
  when: install_etcd
  ansible.builtin.include_tasks: install/etcd.yml

- name: Install runc
  when: install_runc
  ansible.builtin.include_tasks: install/runc.yml

- name: Install kubernetes
  when: install_kubernetes
  ansible.builtin.include_tasks: install/kubernetes.yml
