---
# - name: import os specific variables
#   ansible.builtin.include_vars: vars/{{ ansible_distribution | lower }}.yml
#
# - name: preflight
#   ansible.builtin.include_tasks: preflight/main.yml
#
# - name: install completion scripts
#   ansible.builtin.include_tasks: install/bash_completion.yml
#
# - name: install CNI plugins
#   ansible.builtin.include_tasks: install/cni_plugins.yml

- name: install containerd
  ansible.builtin.include_tasks: install/containerd.yml

- name: install critools
  ansible.builtin.include_tasks: install/critools.yml

- name: install etcd
  ansible.builtin.include_tasks: install/etcd.yml

- name: install runc
  ansible.builtin.include_tasks: install/runc.yml

- name: install kubernetes
  ansible.builtin.include_tasks: install/kubernetes.yml
