---
- name: install keepalived
  ansible.builtin.include_tasks: install/{{ ansible_distribution | lower }}.yml

- name: push keepalived.conf
  notify: reload keepalived
  ansible.builtin.template:
    backup: yes
    dest: /etc/keepalived/keepalived.conf
    group: root
    mode: 0644
    owner: root
    src: etc/keepalived/keepalived.conf
    validate: /usr/sbin/keepalived --config-test --use-file %s

- name: enable service
  ansible.builtin.systemd:
    enabled: yes
    name: keepalived
    state: started