# vi: set ft=yaml.ansible :
---
- name: Converge
  any_errors_fatal: true
  become: true
  hosts: all
  tasks:
    - name: Include role
      ansible.builtin.include_role:
        name: glacion.kubernetes
