# vi: set ft=yaml.ansible :
---
- name: Prepare image
  any_errors_fatal: true
  hosts: default
  become: true
  roles:
    - kubernetes

# TODO: Clean _everything_
- name: Clean up
  any_errors_fatal: true
  become: true
  hosts: default
  tasks:
    - name: Clear cloud-init
      changed_when: false
      ansible.builtin.command: cloud-init clean
