---
- name: prepare image
  any_errors_fatal: true
  hosts: default
  become: true
  roles:
    - ../roles/kubernetes

# TODO: Clean _everything_
- name: clean up
  any_errors_fatal: true
  hosts: default
  become: true
  tasks:
    - name: clear cloud-init
      ansible.builtin.command: cloud-init clean
