---
- name: prepare image
  any_errors_fatal: yes
  hosts: default
  become: yes
  roles:
    - ../roles/kubernetes
 
# TODO: Clean _everything_
- name: clean up
  any_errors_fatal: yes
  hosts: default
  become: yes
  tasks:
    - name: clear cloud-init
      ansible.builtin.command: cloud-init clean